//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Security;
using System.Web.UI;
using System.Web.WebPages;
using System.Web.WebPages.Html;

public class _Page_CourseHomePage_cshtml : System.Web.WebPages.WebPage {
private static object @__o;
#line hidden
public _Page_CourseHomePage_cshtml() {
}
protected System.Web.HttpApplication ApplicationInstance {
get {
return ((System.Web.HttpApplication)(Context.ApplicationInstance));
}
}
public override void Execute() {

#line 1 "C:\Users\amnaraya.ITRON\AppData\Local\Temp\45D12DC7B2907DAA769C9935CB19F840414F\3\MVC_FinaLProject2\Views\Course\CourseHomePage.cshtml"
__o = model;


#line default
#line hidden

#line 2 "C:\Users\amnaraya.ITRON\AppData\Local\Temp\45D12DC7B2907DAA769C9935CB19F840414F\3\MVC_FinaLProject2\Views\Course\CourseHomePage.cshtml"
  
    ViewBag.Title = "CourseHomePage";
    Layout = "~/Views/Admin/AdminLayoutpage.cshtml";


#line default
#line hidden

#line 3 "C:\Users\amnaraya.ITRON\AppData\Local\Temp\45D12DC7B2907DAA769C9935CB19F840414F\3\MVC_FinaLProject2\Views\Course\CourseHomePage.cshtml"
    foreach (var course in Model)
    {
        

#line default
#line hidden

#line 4 "C:\Users\amnaraya.ITRON\AppData\Local\Temp\45D12DC7B2907DAA769C9935CB19F840414F\3\MVC_FinaLProject2\Views\Course\CourseHomePage.cshtml"
           __o = course.Title;


#line default
#line hidden

#line 5 "C:\Users\amnaraya.ITRON\AppData\Local\Temp\45D12DC7B2907DAA769C9935CB19F840414F\3\MVC_FinaLProject2\Views\Course\CourseHomePage.cshtml"
          __o = course.Description;


#line default
#line hidden

#line 6 "C:\Users\amnaraya.ITRON\AppData\Local\Temp\45D12DC7B2907DAA769C9935CB19F840414F\3\MVC_FinaLProject2\Views\Course\CourseHomePage.cshtml"
            if (CurrentUserRepository.CurrentUser == null)
           {
            

#line default
#line hidden

#line 7 "C:\Users\amnaraya.ITRON\AppData\Local\Temp\45D12DC7B2907DAA769C9935CB19F840414F\3\MVC_FinaLProject2\Views\Course\CourseHomePage.cshtml"
                          course.LearnMoreLink;


#line default
#line hidden

#line 8 "C:\Users\amnaraya.ITRON\AppData\Local\Temp\45D12DC7B2907DAA769C9935CB19F840414F\3\MVC_FinaLProject2\Views\Course\CourseHomePage.cshtml"
                                                                            }
            else
            {
            

#line default
#line hidden

#line 9 "C:\Users\amnaraya.ITRON\AppData\Local\Temp\45D12DC7B2907DAA769C9935CB19F840414F\3\MVC_FinaLProject2\Views\Course\CourseHomePage.cshtml"
                             rse.LearnMoreLink;


#line default
#line hidden

#line 10 "C:\Users\amnaraya.ITRON\AppData\Local\Temp\45D12DC7B2907DAA769C9935CB19F840414F\3\MVC_FinaLProject2\Views\Course\CourseHomePage.cshtml"
                                                                            }

#line default
#line hidden

#line 11 "C:\Users\amnaraya.ITRON\AppData\Local\Temp\45D12DC7B2907DAA769C9935CB19F840414F\3\MVC_FinaLProject2\Views\Course\CourseHomePage.cshtml"
              
    }

#line default
#line hidden
}
}
}
