//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Security;
using System.Web.UI;
using System.Web.WebPages;
using System.Web.WebPages.Html;

public class _Page_AdminHomePage_cshtml : System.Web.WebPages.WebPage {
#line hidden
public _Page_AdminHomePage_cshtml() {
}
protected System.Web.HttpApplication ApplicationInstance {
get {
return ((System.Web.HttpApplication)(Context.ApplicationInstance));
}
}
public override void Execute() {

#line 1 "C:\Users\amnaraya.ITRON\AppData\Local\Temp\45D12DC7B2907DAA769C9935CB19F840414F\3\MVC_FinaLProject2\Views\Admin\AdminHomePage.cshtml"
  
    ViewBag.Title = "AdminHomePage";
    Layout = "~/Views/Admin/AdminLayoutpage.cshtml";


#line default
#line hidden
}
}
}
