//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Security;
using System.Web.UI;
using System.Web.WebPages;
using System.Web.WebPages.Html;

#line 4 "C:\Users\amnaraya.ITRON\AppData\Local\Temp\45D12DC7B2907DAA769C9935CB19F840414F\3\MVC_FinaLProject2\Views\Shared\_Layout.cshtml"
using MVC_FinaLProject2.Repository;

#line default
#line hidden

public class _Page__Layout_cshtml : System.Web.WebPages.WebPage {
private static object @__o;
#line hidden
public _Page__Layout_cshtml() {
}
protected System.Web.HttpApplication ApplicationInstance {
get {
return ((System.Web.HttpApplication)(Context.ApplicationInstance));
}
}
public override void Execute() {

#line 1 "C:\Users\amnaraya.ITRON\AppData\Local\Temp\45D12DC7B2907DAA769C9935CB19F840414F\3\MVC_FinaLProject2\Views\Shared\_Layout.cshtml"
      __o = ViewBag.Title;


#line default
#line hidden

#line 2 "C:\Users\amnaraya.ITRON\AppData\Local\Temp\45D12DC7B2907DAA769C9935CB19F840414F\3\MVC_FinaLProject2\Views\Shared\_Layout.cshtml"
__o = Styles.Render("~/Content/css");


#line default
#line hidden

#line 3 "C:\Users\amnaraya.ITRON\AppData\Local\Temp\45D12DC7B2907DAA769C9935CB19F840414F\3\MVC_FinaLProject2\Views\Shared\_Layout.cshtml"
__o = Scripts.Render("~/bundles/modernizr");


#line default
#line hidden

#line 5 "C:\Users\amnaraya.ITRON\AppData\Local\Temp\45D12DC7B2907DAA769C9935CB19F840414F\3\MVC_FinaLProject2\Views\Shared\_Layout.cshtml"
                    if (CurrentUserRepository.CurrentUser != null)
                    {
                        

#line default
#line hidden

#line 6 "C:\Users\amnaraya.ITRON\AppData\Local\Temp\45D12DC7B2907DAA769C9935CB19F840414F\3\MVC_FinaLProject2\Views\Shared\_Layout.cshtml"
                                                                                   __o = CurrentUserRepository.CurrentUser.UserName;


#line default
#line hidden

#line 7 "C:\Users\amnaraya.ITRON\AppData\Local\Temp\45D12DC7B2907DAA769C9935CB19F840414F\3\MVC_FinaLProject2\Views\Shared\_Layout.cshtml"
                              
                    }

#line default
#line hidden

#line 8 "C:\Users\amnaraya.ITRON\AppData\Local\Temp\45D12DC7B2907DAA769C9935CB19F840414F\3\MVC_FinaLProject2\Views\Shared\_Layout.cshtml"
                   __o = Html.ActionLink("Home", "AdminHomePage", "Admin", new { area = "" }, new { @class = "nav-link" });


#line default
#line hidden

#line 9 "C:\Users\amnaraya.ITRON\AppData\Local\Temp\45D12DC7B2907DAA769C9935CB19F840414F\3\MVC_FinaLProject2\Views\Shared\_Layout.cshtml"
                   __o = 

#line default
#line hidden

#line 11 "C:\Users\amnaraya.ITRON\AppData\Local\Temp\45D12DC7B2907DA;


#line default
#line hidden

#line 10 "C:\Users\amnaraya.ITRON\AppData\Local\Temp\45D12DC7B2907DAA769C9935CB19F840414F\3\MVC_FinaLProject2\Views\Shared\_Layout.cshtml"
                   __o = 

#line default
#line hidden

#line 12 "C:\Users\amnaraya.ITRON\AppData\Local\Temp\45D12D;


#line default
#line hidden

#line 11 "C:\Users\amnaraya.ITRON\AppData\Local\Temp\45D12DC7B2907DAA769C9935CB19F840414F\3\MVC_FinaLProject2\Views\Shared\_Layout.cshtml"
                    if (CurrentUserRepository.CurrentUser == null)
                    {
                        

#line default
#line hidden

#line 12 "C:\Users\amnaraya.ITRON\AppData\Local\Temp\45D12DC7B2907DAA769C9935CB19F840414F\3\MVC_FinaLProject2\Views\Shared\_Layout.cshtml"
                                                                                
                        

#line default
#line hidden

#line 13 "C:\Users\amnaraya.ITRON\AppData\Local\Temp\45D12DC7B2907DAA769C9935CB19F840414F\3\MVC_FinaLProject2\Views\Shared\_Layout.cshtml"
                       __o = Html.ActionLink("Login", "Login", "Login", new { area = "" }, new { @class = "nav-link" });


#line default
#line hidden

#line 14 "C:\Users\amnaraya.ITRON\AppData\Local\Temp\45D12DC7B2907DAA769C9935CB19F840414F\3\MVC_FinaLProject2\Views\Shared\_Layout.cshtml"
                             
                        

#line default
#line hidden

#line 15 "C:\Users\amnaraya.ITRON\AppData\Local\Temp\45D12DC7B2907DAA769C9935CB19F840414F\3\MVC_FinaLProject2\Views\Shared\_Layout.cshtml"
                       __o = Html.ActionLink("Register now", "AddDetails", "Registration", new { area = "" }, new { @class = "nav-link" });


#line default
#line hidden

#line 16 "C:\Users\amnaraya.ITRON\AppData\Local\Temp\45D12DC7B2907DAA769C9935CB19F840414F\3\MVC_FinaLProject2\Views\Shared\_Layout.cshtml"
                             
                    }
                    else
                    {
                        

#line default
#line hidden

#line 17 "C:\Users\amnaraya.ITRON\AppData\Local\Temp\45D12DC7B2907DAA769C9935CB19F840414F\3\MVC_FinaLProject2\Views\Shared\_Layout.cshtml"
                                                                                    
                        

#line default
#line hidden

#line 18 "C:\Users\amnaraya.ITRON\AppData\Local\Temp\45D12DC7B2907DAA769C9935CB19F840414F\3\MVC_FinaLProject2\Views\Shared\_Layout.cshtml"
                       __o = Html.ActionLink("Sign Out", "Logout", "Login", new { area = "" }, new { @class = "nav-link" });


#line default
#line hidden

#line 19 "C:\Users\amnaraya.ITRON\AppData\Local\Temp\45D12DC7B2907DAA769C9935CB19F840414F\3\MVC_FinaLProject2\Views\Shared\_Layout.cshtml"
                             
                    }

#line default
#line hidden

#line 20 "C:\Users\amnaraya.ITRON\AppData\Local\Temp\45D12DC7B2907DAA769C9935CB19F840414F\3\MVC_FinaLProject2\Views\Shared\_Layout.cshtml"
   __o = nav-link" });


#line default
#line hidden

#line 21 "C:\Users\amnaraya.ITRON\AppData\Local\Temp\45D12DC7B2907DAA769C9935CB19F840414F\3\MVC_FinaLProject2\Views\Shared\_Layout.cshtml"
__o =  = RenderBody();


#line defaul;


#line default
#line hidden

#line 22 "C:\Users\amnaraya.ITRON\AppData\Local\Temp\45D12DC7B2907DAA769C9935CB19F840414F\3\MVC_FinaLProject2\Views\Shared\_Layout.cshtml"
__o = undles/jquery");


#line default
;


#line default
#line hidden

#line 23 "C:\Users\amnaraya.ITRON\AppData\Local\Temp\45D12DC7B2907DAA769C9935CB19F840414F\3\MVC_FinaLProject2\Views\Shared\_Layout.cshtml"
__o = les/bootstrap");


#line default
#lin;


#line default
#line hidden
}
}
}
\AppData\Local\Temp\45D12DC7B2907DAA769C9935CB19F840414F\3\MVC_FinaLProject2\Views\Shared\_Layout.cshtml"
__o = RenderSection("scripts", required: false);


#line default
#line hidden
}
}
}
